-- ============================================================
-- 01_create_tables.sql
-- Financial Performance & Profitability Analysis
-- Database: PostgreSQL 18
--
-- Creates the 5 raw tables. Every column is loaded as TEXT first
-- (the source files contain commas / blanks); numeric casting is
-- done later in 03_views.sql.
-- join_key is the 1:1 key shared by all five tables.
-- ============================================================

DROP TABLE IF EXISTS annual_pl_1 CASCADE;

CREATE TABLE annual_pl_1 (
    "Name" TEXT,
    "BSE Code" TEXT,
    "NSE Code" TEXT,
    "Industry" TEXT,
    "Current Price" TEXT,
    "Sales" TEXT,
    "OPM" TEXT,
    "Profit after tax" TEXT,
    "Return on capital employed" TEXT,
    "EPS" TEXT,
    "Change in promoter holding" TEXT,
    "Sales last year" TEXT,
    "Operating profit last year" TEXT,
    "Other income last year" TEXT,
    "EBIDT last year" TEXT,
    "Depreciation last year" TEXT,
    "EBIT last year" TEXT,
    "Interest last year" TEXT,
    "Profit before tax last year" TEXT,
    "Tax last year" TEXT,
    "Profit after tax last year" TEXT,
    "Extraordinary items last year" TEXT,
    "Net Profit last year" TEXT,
    "Dividend last year" TEXT,
    "Material cost last year" TEXT,
    "Employee cost last year" TEXT,
    "OPM last year" TEXT,
    "NPM last year" TEXT,
    "Operating profit" TEXT,
    "Interest" TEXT,
    "Depreciation" TEXT,
    "EPS last year" TEXT,
    "EBIT" TEXT,
    "Net profit" TEXT,
    "Current Tax" TEXT,
    "Tax" TEXT,
    "Other income" TEXT,
    "Last annual result date" TEXT,
    "Sales preceding year" TEXT,
    "Operating profit preceding year" TEXT,
    "Other income preceding year" TEXT,
    "EBIDT preceding year" TEXT,
    "Depreciation preceding year" TEXT,
    "EBIT preceding year" TEXT,
    "Interest preceding year" TEXT,
    "Profit before tax preceding year" TEXT,
    "Tax preceding year" TEXT,
    "Profit after tax preceding year" TEXT,
    "Extraordinary items preceding year" TEXT,
    "Net Profit preceding year" TEXT,
    "Dividend preceding year" TEXT,
    "OPM preceding year" TEXT,
    "NPM preceding year" TEXT,
    "EPS preceding year" TEXT,
    "Sales preceding 12months" TEXT,
    "Net profit preceding 12months" TEXT,
    "Market Capitalization" TEXT,
    "join_key" TEXT PRIMARY KEY
);

DROP TABLE IF EXISTS balance_sheet CASCADE;

CREATE TABLE balance_sheet (
    "Name" TEXT,
    "BSE Code" TEXT,
    "NSE Code" TEXT,
    "Industry" TEXT,
    "Current Price" TEXT,
    "Debt" TEXT,
    "Equity capital" TEXT,
    "Preference capital" TEXT,
    "Reserves" TEXT,
    "Secured loan" TEXT,
    "Unsecured loan" TEXT,
    "Balance sheet total" TEXT,
    "Gross block" TEXT,
    "Revaluation reserve" TEXT,
    "Accumulated depreciation" TEXT,
    "Net block" TEXT,
    "Capital work in progress" TEXT,
    "Investments" TEXT,
    "Current assets" TEXT,
    "Current liabilities" TEXT,
    "Book value of unquoted investments" TEXT,
    "Market value of quoted investments" TEXT,
    "Contingent liabilities" TEXT,
    "Total Assets" TEXT,
    "Working capital" TEXT,
    "Lease liabilities" TEXT,
    "Inventory" TEXT,
    "Trade receivables" TEXT,
    "Face value" TEXT,
    "Cash Equivalents" TEXT,
    "Advance from Customers" TEXT,
    "Trade Payables" TEXT,
    "Number of equity shares preceding year" TEXT,
    "Debt preceding year" TEXT,
    "Working capital preceding year" TEXT,
    "Net block preceding year" TEXT,
    "Gross block preceding year" TEXT,
    "Capital work in progress preceding year" TEXT,
    "Working capital 3Years back" TEXT,
    "Working capital 5Years back" TEXT,
    "Working capital 7Years back" TEXT,
    "Working capital 10Years back" TEXT,
    "Debt 3Years back" TEXT,
    "Debt 5Years back" TEXT,
    "Debt 7Years back" TEXT,
    "Debt 10Years back" TEXT,
    "Net block 3Years back" TEXT,
    "Net block 5Years back" TEXT,
    "Net block 7Years back" TEXT,
    "Market Capitalization" TEXT,
    "join_key" TEXT PRIMARY KEY
);

DROP TABLE IF EXISTS cash_flow CASCADE;

CREATE TABLE cash_flow (
    "Name" TEXT,
    "BSE Code" TEXT,
    "NSE Code" TEXT,
    "Industry" TEXT,
    "Current Price" TEXT,
    "Cash from operations last year" TEXT,
    "Free cash flow last year" TEXT,
    "Cash from investing last year" TEXT,
    "Cash from financing last year" TEXT,
    "Net cash flow last year" TEXT,
    "Cash beginning of last year" TEXT,
    "Cash end of last year" TEXT,
    "Free cash flow preceding year" TEXT,
    "Cash from operations preceding year" TEXT,
    "Cash from investing preceding year" TEXT,
    "Cash from financing preceding year" TEXT,
    "Net cash flow preceding year" TEXT,
    "Cash beginning of preceding year" TEXT,
    "Cash end of preceding year" TEXT,
    "Free cash flow 3years" TEXT,
    "Free cash flow 5years" TEXT,
    "Free cash flow 7years" TEXT,
    "Free cash flow 10years" TEXT,
    "Operating cash flow 3years" TEXT,
    "Operating cash flow 5years" TEXT,
    "Operating cash flow 7years" TEXT,
    "Operating cash flow 10years" TEXT,
    "Investing cash flow 10years" TEXT,
    "Investing cash flow 7years" TEXT,
    "Investing cash flow 5years" TEXT,
    "Investing cash flow 3years" TEXT,
    "Cash 3Years back" TEXT,
    "Cash 5Years back" TEXT,
    "Cash 7Years back" TEXT,
    "Market Capitalization" TEXT,
    "join_key" TEXT PRIMARY KEY
);

DROP TABLE IF EXISTS financial_ratios CASCADE;

CREATE TABLE financial_ratios (
    "Name" TEXT,
    "BSE Code" TEXT,
    "NSE Code" TEXT,
    "Industry" TEXT,
    "Current Price" TEXT,
    "Market Capitalization" TEXT,
    "Price to Earning" TEXT,
    "Dividend yield" TEXT,
    "Price to book value" TEXT,
    "Return on assets" TEXT,
    "Debt to equity" TEXT,
    "Return on equity" TEXT,
    "Promoter holding" TEXT,
    "Earnings yield" TEXT,
    "Pledged percentage" TEXT,
    "Industry PE" TEXT,
    "Enterprise Value" TEXT,
    "Number of equity shares" TEXT,
    "Book value" TEXT,
    "Inventory turnover ratio" TEXT,
    "Quick ratio" TEXT,
    "Exports percentage" TEXT,
    "Piotroski score" TEXT,
    "G Factor" TEXT,
    "Asset Turnover Ratio" TEXT,
    "Financial leverage" TEXT,
    "Number of Shareholders" TEXT,
    "Unpledged promoter holding" TEXT,
    "Return on invested capital" TEXT,
    "Debtor days" TEXT,
    "Industry PBV" TEXT,
    "Credit rating" TEXT,
    "Working Capital Days" TEXT,
    "Earning Power" TEXT,
    "Graham Number" TEXT,
    "Cash Conversion Cycle" TEXT,
    "Days Payable Outstanding" TEXT,
    "Days Receivable Outstanding" TEXT,
    "Days Inventory Outstanding" TEXT,
    "Public holding" TEXT,
    "FII holding" TEXT,
    "Change in FII holding" TEXT,
    "Change in DII holding" TEXT,
    "DII holding" TEXT,
    "Book value preceding year" TEXT,
    "Return on capital employed preceding year" TEXT,
    "Return on assets preceding year" TEXT,
    "Return on equity preceding year" TEXT,
    "Number of Shareholders preceding quarter" TEXT,
    "join_key" TEXT PRIMARY KEY
);

DROP TABLE IF EXISTS quarterly_financials CASCADE;

CREATE TABLE quarterly_financials (
    "Name" TEXT,
    "BSE Code" TEXT,
    "NSE Code" TEXT,
    "Industry" TEXT,
    "Current Price" TEXT,
    "Sales latest quarter" TEXT,
    "Profit after tax latest quarter" TEXT,
    "YOY Quarterly sales growth" TEXT,
    "YOY Quarterly profit growth" TEXT,
    "Sales growth" TEXT,
    "Profit growth" TEXT,
    "Operating profit latest quarter" TEXT,
    "Other income latest quarter" TEXT,
    "EBIDT latest quarter" TEXT,
    "Depreciation latest quarter" TEXT,
    "EBIT latest quarter" TEXT,
    "Interest latest quarter" TEXT,
    "Profit before tax latest quarter" TEXT,
    "Tax latest quarter" TEXT,
    "Extraordinary items latest quarter" TEXT,
    "Net Profit latest quarter" TEXT,
    "GPM latest quarter" TEXT,
    "OPM latest quarter" TEXT,
    "NPM latest quarter" TEXT,
    "Equity Capital latest quarter" TEXT,
    "EPS latest quarter" TEXT,
    "Operating profit 2quarters back" TEXT,
    "Operating profit 3quarters back" TEXT,
    "Sales 2quarters back" TEXT,
    "Sales 3quarters back" TEXT,
    "Net profit 2quarters back" TEXT,
    "Net profit 3quarters back" TEXT,
    "Operating profit growth" TEXT,
    "Last result date" TEXT,
    "Expected quarterly sales growth" TEXT,
    "Expected quarterly sales" TEXT,
    "Expected quarterly operating profit" TEXT,
    "Expected quarterly net profit" TEXT,
    "Expected quarterly EPS" TEXT,
    "Sales preceding quarter" TEXT,
    "Operating profit preceding quarter" TEXT,
    "Other income preceding quarter" TEXT,
    "EBIDT preceding quarter" TEXT,
    "Depreciation preceding quarter" TEXT,
    "EBIT preceding quarter" TEXT,
    "Interest preceding quarter" TEXT,
    "Profit before tax preceding quarter" TEXT,
    "Tax preceding quarter" TEXT,
    "Profit after tax preceding quarter" TEXT,
    "Extraordinary items preceding quarter" TEXT,
    "Net Profit preceding quarter" TEXT,
    "OPM preceding quarter" TEXT,
    "NPM preceding quarter" TEXT,
    "Equity Capital preceding quarter" TEXT,
    "EPS preceding quarter" TEXT,
    "Market Capitalization" TEXT,
    "join_key" TEXT PRIMARY KEY
);
